### ISSUE TITLE
Unable to add a block in Moodle 2.9 together with mod_attendance (commit 24.08.2015)

### ISSUE THREAD

**Issue by Kathrin84** [danmarsden/moodle-block_attendance#10]
Hi Dan,

I took both, the newest versions from block_attendance and mod_attendance from gitHub. Always when I wanted to add the block to my course, following notice/error occured and crashed my course:

Notice: Undefined property: attendance::$perm in /var/www/html/moodle_dev/blocks/attendance/block_attendance.php on line 79

Fatal error: Call to a member function can_take() on a non-object in /var/www/html/moodle_dev/blocks/attendance/block_attendance.php on line 79

Kind regards,
Kathrin

**Comment by Syxton** [comment]
We are also seeing this issue.  It also makes it impossible to view assignments in those courses. This is a serious blocker for us.

**Comment by glydetech** [comment]
I'm seeing the same issue. I've checked over the mod_attendance and 'perm' doesn't appear to be defined as an object property. My workaround is simply commenting out the conditionals in blocks/attendance/block_attendance.

**Comment by Canx** [comment]
Same problem here, I will also try removing conditionals

**Comment by danmarsden** [comment]
sorry guys, I've been working on the attendance activity in the master branch and tidying up some weird code. I didn't see this earlier because for some reason I wasn't subscribed to the issues tracker in github for this project (until now) which seems really weird... I'll get this sorted now.

**Comment by danmarsden** [comment]
Fix now in the master branch here. You will also need to update the attendance activity mod with the latest from the master branch because I've added a dependency to the block. Thanks for the report and apologies for the delay on this one!

**Comment by Kathrin84** [comment]
Hi Dan,
thanks for resolving this issue. :)

**Comment by Kathrin84** [comment]
Could you please update your code in the Moodle plugin repo. There, the code is not up to date. Updating plugins with the Moodle internal procedure is way more comfortable.
That would be great!

**Comment by danmarsden** [comment]
not yet.... you must have picked up the mod_attendance plugin from the github repo to get this error in the first place. I don't update the plugins repo immediately after bumping the version in github to allow more advanced users to pick up any issues before we release it to the masses. :-)

**Comment by glydetech** [comment]
This appears to fix the issue. Thanks!
