### ISSUE TITLE
block_attendance: Incorrect user attendance data being displayed

### ISSUE THREAD

**Issue by jebarviabb** [danmarsden/moodle-block_attendance#11]
Hi Dan,

With the recent upgrade of mod_attendance, the function construct_full_user_stat_html_table has been modified (mod/attendance/renderhelpers.php). This is now the current function definition:
`function construct_full_user_stat_html_table($attendance, $user) {`

However,  it is being called this way (blocks/attendance/block_attendance.php):
`$this->content->text .= construct_full_user_stat_html_table($attinst, $COURSE, $USER, $cm);`

Which displays incorrect data due to $COURSE being passed instead of $USER.

**Comment by jebarviabb** [comment]
This is my fix for this issue.
`diff --git a/blocks/attendance/block_attendance.php b/blocks/attendance/block_attendance.php
index a409141..13f6d01 100644
--- a/blocks/attendance/block_attendance.php
+++ b/blocks/attendance/block_attendance.php
@@ -95,7 +95,7 @@ class block_attendance extends block_base {
 
             if (has_capability('mod/attendance:canbelisted', $context, null, false) &&
                 has_capability('mod/attendance:view', $context)) {
-                $this->content->text .= construct_full_user_stat_html_table($attinst, $COURSE, $USER, $cm);
+                $this->content->text .= construct_full_user_stat_html_table($attinst, $USER);
             }
             $this->content->text .= "<br />";
         }
`
I am not sure if I should create a Moodle Tracker item for this so as it gets integrated upstream.

Please advise.

**Comment by danmarsden** [comment]
thanks for the report - I've pushed a fix here, will tidy up the branches a bit and release it in the plugins db.

The Moodle Tracker is not used for tracking bugs with the attendance plugin. We use the github issue tracker here.

**Comment by jebarviabb** [comment]
Thanks for that Dan. Have a great day.
