### ISSUE TITLE
Attendance activities in recycle bin should not show in block.

### ISSUE THREAD

**Issue by tfradet** [danmarsden/moodle-block_attendance#14]
If I had more than one Attendance activity to the course, and after I delete an Attendance activity, it will always be shown on the bloc. If I try to clic on bloc links related to the deleted Attendance activity, an alert is displayed on the top of course content page : "Suppression d'activité en cours..." (in english : "deletion of activity in progress...") but noting changes. 

<img width="1409" alt="capture d ecran 2018-02-07 a 11 07 03" src="https://user-images.githubusercontent.com/16959418/35910534-2576932a-0bf7-11e8-979d-c79dcced9fdb.png">

**Comment by danmarsden** [comment]
thanks for the report - I had a similar issue reported with the recycle bin in the activity module last week - should be an easy fix.

**Comment by danmarsden** [comment]
just pushed a fix into github that should fix this - will release a new version in the plugins db with this fix in a couple of weeks.
