### ISSUE TITLE
Cron failure Moodle 3.2

### ISSUE THREAD

**Issue by jevilla94** [danmarsden/moodle-block_attendance#15]
Cordial greeting

I have recently installed this plugin in my version 3.2 moodle. During the execution of the cron it returns an error that is very disturbing.
Could you tell me how to solve this fault or why it occurs?

During the execution of the cron the following message returns:
"Execute scheduled task: Consultar sesiones de asistencia que requieran registro automático (mod_attendance\task\auto_mark)
... started 16:18:52. Current memory use 15.4MB.
No unmarked status configured for session id: 797
...
0 session status updated
!!! Detectado un error de codificación, debe ser corregido por un programador: A lock was created but not released at:
[dirroot]/lib/classes/task/manager.php on line 483

 Code should look like:

 $factory = \core\lock\lock_config::get_lock_factory('type');
 $lock = $factory-&gt;get_lock(Resource id #583);
 $lock-&gt;release();  // Locks must ALWAYS be released like this.

 !!!
"
I am attentive to your indications, thank you very much for your attention

**Comment by danmarsden** [comment]
Please don't add new plugins to old unsupported Moodle versions. Any time you have available to work on your Moodle site should be spent on upgrading your Moodle site to a supported release before you look at adding other plugins.

Moodle 3.2 has been out of support for 2 years and contains a number of known security issues that could allow a malicious user to seriously compromise your site.

This could be an issue with your 3.2 site or the attendance plugin, but I don't provide support for unsupported Moodle releases - except to say the "fix" is to upgrade your Moodle site to a supported release and then use the latest version of the attendance plugin. Good luck!
