### ISSUE TITLE
BSSID instead of IP-address

### ISSUE THREAD

**Issue by torrilhon** [danmarsden/moodle-block_attendance#17]
I am very interested in using your module to track attendance of students within Moodle. However, in my university the option of restricting the IP-addresses to avoid external registrations is not possible, because the IPs of the students can not be fixed or assigned to specific locations.

Another possibility is to extract the BSSID of the access points of the student's phone/PC when connected to the universities WiFi. I would like to be able to give a list of admissible BSSID (Mac-adresses) of APs in the vicinity of the class room (instead of IPs) which are cross-checked by moodle on the student's devices when they register their attendance.

Is it possible that you extend the implementation of you module?

**Comment by danmarsden** [comment]
I can't see how this would work - the users SSID is not passed in the request headers from their browser to the web server - so "Moodle" can't find this information out. Usually in this sort of scenario I've seen organisations add the full IP range of known addresses, and then use the QR Code rotation process for marking sessions - that way it forces both the use of the university network, and access to the current QR code... of course that doesn't stop people bringing in multiple devices and taking attendance for their friends.

We only get the users originating IP address - The only way I can think this would be possible is to have some form of API that allows Moodle to ask your network infrastructure "what access point does this IP address use" - but that would be heavily dependent on your network infrastructure and heavily custom to your specific environment (and hard to make it generic/useful for other organisations not using the same infrastructure.)

Of course - I'm open to ideas if you have a network engineer that has further ideas on how we could obtain this information safely and reliably from the webserver/moodle.

Also - keep in mind I don't tend to do "feature development" like this for free.. :-)

**Comment by danmarsden** [comment]
I see you've also posted in the community forums... lets close this here and continue any further discussion there....
