### ISSUE TITLE
Add tags to GitHub

### ISSUE THREAD

**Issue by JokaJukka** [danmarsden/moodle-block_attendance#18]
Hey there!
We are using your plugin on our site as a git submodule - it is hard for us to track if a new version is out, and which commit does it correspond to. Would it be possible to add tags to corresponding commits, upon which the releases are based?

Thank you,
Miroslav Jarý
FEE CTU in Prague

**Comment by danmarsden** [comment]
Thanks for the request, I maintain a lot of different plugins as a volunteer both in my personal repo and in the catalyst org one, we use git branches and have been rolling out the automatic publishing to moodle.org plugins db process but have no plans to use tags ay this stage. Thanks!
