### ISSUE TITLE
MOODLE_311_STABLE branch fails to installl in a moodle just upgraded to 3.11 in the same branch

### ISSUE THREAD

**Issue by IJOL** [danmarsden/moodle-block_attendance#19]
Salida de depuración habilitada
Descargando mod_attendance ... 
 <- https://moodle.org/plugins/download.php/28433/mod_attendance_moodle311_2021082610.zip
 -> /var/www/moodledata/temp/core_plugin/code_manager/distfiles/5c554750d2795101a62ef0832de7e6ff.zip ... OK
Validando mod_attendance ... Error
  [OK] Nombre del módulo externo que se debe instalar [attendance]  
  [OK] Versión del módulo externo [2021082610] 
  [Error] Versión de Moodle requerida [2021051700] 
Instalación abortada debido a error de validación

contents of the version.php of the moodle in branch MOODLE_311_STABLE are as follows:

$version  = 2021051715.06;              // 20210517      = branching date YYYYMMDD - do not modify!
                                        //         RR    = release increments - 00 in DEV branches.
                                        //           .XX = incremental changes.
$release  = '3.11.15+ (Build: 20230721)';// Human-friendly version name
$branch   = '311';

**Comment by danmarsden** [comment]
Hard to say what's happening there without digging into it further - but you've reported this in the "block_attendance" repository - but your path above looks like the "mod_attendance" plugin - (not block_attendance) - so I'm closing this as it's in the wrong place... but... if you report the same issue in the "right place" (mod_attendance repo)  I'm unlikely to look much further unless you are able to provide more information. - thanks!

**Comment by IJOL** [comment]
Oops, wrong repo, sorry just posted the report to the correct one...
