### ISSUE TITLE
Compatibility with Moodle 4.3

### ISSUE THREAD

**Issue by michael-milette** [danmarsden/moodle-block_attendance#20]
Hi @danmarsden ,

When do you think you might have a version compatible with Moodle 4.3?

Based on my own initial quick test, most of it looks pretty good. The only issue I have come across so far is that I see the following error message when I go to take attendance:

<img width="400" alt="image" src="https://github.com/danmarsden/moodle-block_attendance/assets/3808579/f7478f2c-6583-43cd-9f94-64e5d2df7d6a">

Here is the error message from the above screenshot:

user_preference_allow_ajax_update() is deprecated. Please use the "core_user/repository" module instead.
line 41 of \lib\ajax\ajaxlib.php: call to debugging()
line 506 of \mod\attendance\classes\output\renderer.php: call to user_preference_allow_ajax_update()
line 497 of \lib\outputrenderers.php: call to mod_attendance\output\renderer->render_take_data()
line 104 of \mod\attendance\take.php: call to plugin_renderer_base->render()

Note: I am using Moodle 4.3 running on PHP 8.2.

Best regards,

Michael Milette

**Comment by danmarsden** [comment]
@michael-milette - we only provide timeframes to paying customers ;-)

Seriously though it probably works as-is but feel free to report any specific issues you find in testing. Thanks!
